github-pages:
  directory: .  # Save index.html file at the root of gh-pages

storage:
  capacity: 25

units:
  - name: allocs/op
    better: lower
    threshold: 0.1
    reduction: median

  - name: B/op
    better: lower
    threshold: 0.1
    reduction: median

  - name: ns/op
    better: lower
    threshold: 0.1
    reduction: median

  - name: MB/s
    better: higher
    threshold: 0.1
    reduction: median
