# More info on config here: https://golangci-lint.run/usage/configuration/#config-file
run:
  concurrency: 8
  timeout: 10m
  issues-exit-code: 1
  tests: true

output:
  formats: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - unnamedResult
      - hugeParam
      - exitAfterDefer
      - ifElseChain
  unused:
    field-writes-are-uses: false
    post-statements-are-reads: false
    # Following parameter does not work correctly: https://github.com/golangci/golangci-lint/issues/4218
    exported-is-used: true
    exported-fields-are-used: false
    # Disable due to false-positive cases
    parameters-are-used: true
    local-variables-are-used: false
    generated-is-used: false

linters:
  disable-all: true
  enable:
    - gofmt
    - goimports
    - errcheck
    - goconst
    # - gosec  # See https://jit.***REMOVED***/browse/SRE-3806
    - govet
    - ineffassign
    - revive
    - typecheck
    - unused
    - gocritic

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-use-default: false
  exclude:
    # _ instead of err checks
    - G104
    # for "public interface + private struct implementation" cases only!
    - exported func .* returns unexported type .*, which can be annoying to use
    - don't use an underscore in package name
    # EXC0001 errcheck: Almost all programs ignore errors on these functions and in most cases it's ok
    - Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*print(f|ln)?|os\.(Un)?Setenv). is not checked
    - should check returned error before deferring
    # EXC0015 revive: Annoying issue about not having a comment. The rare codebase has such comments
    - should have a package comment
    # err variable is used almost every time for error checking
    - declaration of "err" shadows declaration at line
    # remove after stabilization
    - should have a package comment, unless it's in another file for this package
    - exported .+ should have comment.* or be unexported
    - comment on exported const .+ should be of the form

  exclude-files:
    - \.pb\.go$

  exclude-dirs:
    - bin
    - vendor
    - var
    - tmp