services:
  seq-db-store:
    image: ghcr.io/ozontech/seq-db:v0.58.0
    command: --mode store --config /etc/config.example.cluster.yaml
    volumes:
      - "./config.example.cluster.yaml:/etc/config.example.cluster.yaml"
      - "data:/seq-db-data"

  seq-db-proxy:
    image: ghcr.io/ozontech/seq-db:v0.58.0
    ports:
      - "9002:9002"
      - "9004:9004"
      - "9200:9200"
    command: --mode proxy --config /etc/config.example.cluster.yaml
    volumes:
      - "./config.example.cluster.yaml:/etc/config.example.cluster.yaml"
    depends_on:
      - seq-db-store

volumes:
  data: