---
# Source: seq-db/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-name-seq-db
  labels:
    helm.sh/chart: seq-db-0.1.0
    app.kubernetes.io/name: seq-db
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: true
---
# Source: seq-db/templates/seq-ui/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-seq-db
  labels:
    helm.sh/chart: seq-db-0.1.0
    app.kubernetes.io/name: seq-db
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: seq-db
    app.kubernetes.io/instance: release-name
---
# Source: seq-db/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-seq-db
  labels:
    helm.sh/chart: seq-db-0.1.0
    app.kubernetes.io/name: seq-db
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 9002
      targetPort: http
      protocol: TCP
      name: http
    - port: 9004
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    app.kubernetes.io/name: seq-db
    app.kubernetes.io/instance: release-name
---
# Source: seq-db/templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: release-name-seq-db
  labels:
    helm.sh/chart: seq-db-0.1.0
    app.kubernetes.io/name: seq-db
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  updateStrategy:
    type: 
  selector:
    matchLabels:
      app.kubernetes.io/name: seq-db
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      labels:
        helm.sh/chart: seq-db-0.1.0
        app.kubernetes.io/name: seq-db
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/version: "latest"
        app.kubernetes.io/managed-by: Helm
    spec:
      serviceAccountName: release-name-seq-db
      containers:
        - name: seq-db
          image: "ghcr.io/ozontech/seq-db:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 9002
              protocol: TCP
            - name: grpc
              containerPort: 9004
              protocol: TCP
            - name: debug
              containerPort: 9200
              protocol: TCP
