replicaCount: 2

mapping:
  auto: false
  enable_updates: true
  mapping_list:
    - type: "keyword"
      name: "k8s_pod"
    - type: "keyword"
      name: "k8s_namespace"
    - type: "keyword"
      name: "k8s_container"
    - type: "text"
      name: "request"
    - type: "path"
      name: "request_uri"
    - name: "message"
      types:
        - type: "text"
        - title: "keyword"
          type: "keyword"
          size: 18

storage:
  frac_size: "256MiB"
  total_size: "10GiB"

seqproxy:
  ingress:
    enabled: true

sequi:
  ingress:
    enabled: true
  front:
    ingress:
      enabled: true
