storage:
  data_dir: /seq-db-data
  frac_size: 16MiB
  total_size: 64GiB

compaction:
  enabled: true
  workers: 4
  time_window: '30m'
  stcs:
    merge_trigger: 4
    merge_fan_in: 8
    merge_fan_out_size: '156MiB'

mapping:
  path: /configs/mapping.yaml

indexing:
  past_allowed_time_drift: 99000h

sealing:
  lids:
    block_size: 16384

resources:
  skip_fsync: true

compression:
  docs_zstd_compression_level: 3

limits:
  query_rate: 1024
  search_requests: 1024
  bulk_requests: 128
  inflight_bulks: 128
  doc_size: 10MiB
