storage:
  data_dir: /data
  frac_size: 256MiB
  total_size: 100GiB

cluster:
  hot_replicas: 1
  # shuffle_replicas: true
  hot_stores:
    - seq-db-store:9004
  # colds
  # read_stores:
  #   - seq-db-store:9004
  # write_stores:
  #   - seq-db-store:9004

mapping:
  enable_updates: true
  path: /configs/mappings.yaml
  update_period: 5s

slow_logs:
  bulk_threshold: 100ms
  search_threshold: 20ms
  fetch_threshold: 20ms
