{
 "title": "seq-db | elastic | vlogs",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "containers_selector",
    "query": ".*(vlogs|elastic|seq-db|seq-proxy).*"
   },
   {
    "name": "containers",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{name!=\"\",}, name)"
    }
   },
   { "name": "percentile", "label": "P", "query": "0.90,0.95,0.99" }
  ]
 },
 "panels": [
  {
   "title": "File-d Bulk Latency (${percentile}q)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(${percentile}, avg(rate(file_d_pipeline_seqdb_batcher_out_fn_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "seq-db"
    },
    {
     "expr": "histogram_quantile(${percentile}, avg(rate(file_d_pipeline_elasticsearch_batcher_out_fn_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "Elasticsearch"
    }
   ]
  },
  {
   "title": "Output Rate (MiB/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(file_d_pipeline_elasticsearch_output_events_size[$__rate_interval]))",
     "legendFormat": "Elasticsearch"
    },
    {
     "expr": "sum(rate(file_d_pipeline_seqdb_output_events_size[$__rate_interval]))",
     "legendFormat": "seq-db"
    }
   ]
  },
  {
   "title": "Output Rate (docs/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(file_d_pipeline_elasticsearch_input_events_count[$__rate_interval]))",
     "legendFormat": "Elasticsearch"
    },
    {
     "expr": "sum(rate(file_d_pipeline_seqdb_input_events_count[$__rate_interval]))",
     "legendFormat": "seq-db"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\"$containers\"}[$__rate_interval])) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{name=~\"$containers\"}) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(node_disk_usage_bytes{path=~\"$containers_selector\"}) by (path)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Proxy Bulk Latency (${percentile}q)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(${percentile},sum(rate(seq_db_ingestor_bulk_duration_seconds_bucket[$__rate_interval]))by(le,container))\n",
     "legendFormat": "seqproxy"
    }
   ]
  },
  {
   "title": "Proxy Stages Latency (${percentile}q)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(${percentile}, sum(rate(seq_db_ingestor_bulk_duration_seconds_bucket[$__rate_interval]))by (le))",
     "legendFormat": "Total Request Duration"
    },
    {
     "expr": "histogram_quantile(${percentile}, sum(rate(seq_db_ingestor_bulk_request_pool_duration_seconds_bucket[$__rate_interval]))by (le))",
     "legendFormat": "Request Pool Duration"
    },
    {
     "expr": "histogram_quantile(${percentile}, sum(rate(seq_db_ingestor_bulk_parse_duration_seconds_bucket[$__rate_interval]))by (le))",
     "legendFormat": "Parse Duration"
    },
    {
     "expr": "histogram_quantile(${percentile}, sum(rate(seq_db_ingestor_bulk_doc_provide_duration_seconds_bucket[$__rate_interval]))by (le))",
     "legendFormat": "Doc Provide Duration"
    },
    {
     "expr": "histogram_quantile(${percentile}, sum(rate(seq_db_ingestor_bulk_send_attempt_duration_seconds_bucket[$__rate_interval]))by (le))",
     "legendFormat": "Send Attempt Duration"
    },
    {
     "expr": "histogram_quantile(${percentile}, sum(rate(seq_db_ingestor_bulk_read_duration_seconds_bucket[$__rate_interval]))by (le))",
     "legendFormat": "Read Duration"
    }
   ]
  },
  {
   "title": "Store Append Stages Latency (${percentile}q)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(${percentile}, sum(rate(seq_db_store_bulk_stages_seconds_bucket{stage=~\"append.*\"}[$__rate_interval]))by(le,stage))",
     "legendFormat": "{{ stage }}"
    }
   ]
  },
  {
   "title": "Store Indexing Stages Latency (${percentile}q)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(${percentile}, sum(rate(seq_db_store_bulk_stages_seconds_bucket{stage=~\"total_indexing.*\"}[$__rate_interval]))by(le,stage))",
     "legendFormat": "{{ stage }}"
    }
   ]
  }
 ]
}