version: "3"

services:
  seq-db:
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: "8GB"
    image: ghcr.io/ozontech/seq-db:v0.61.0
    ports:
      - '9002:9002'
      - '9200:9200'
    volumes:
      - ./configs/seqdb:/configs
      - seq-db-data:/seq-db-data
    command:
      --mode=single
      --config=/configs/config.yaml

  logs-sender:
    image: golang:1.25-alpine
    deploy:
      resources:
        limits:
          memory: "2GB"
    working_dir: /workspace
    volumes:
      - ../:/workspace
      - ./dataset/:/dataset:ro
    command: go run ./benchmarks/cmd/logs-sender
    environment:
      BULK_URL: http://seq-db:9002/_bulk
      FILE_PATTERN: docs-*.log
      BULK_SIZE: 4096
      INDEX_NAME: logs-index
    depends_on:
      - seq-db

volumes:
  seq-db-data:
