services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.0
    restart: unless-stopped
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro

  node-exporter:
    image: prom/node-exporter:v1.9.1
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'

  du-exporter:
    image: ghcr.io/dundee/disk_usage_exporter/disk_usage_exporter-c4084307c537335c2ddb6f4b9b527422:latest
    restart: unless-stopped
    user: "root"
    volumes:
      - /var/lib/docker/volumes:/var/lib/docker/volumes:ro
      - ./configs/du/du.yml:/config.yml:ro
    command:
      - '--config=/config.yml'

  vmsingle:
    image: victoriametrics/victoria-metrics:v1.115.0-scratch
    ports:
      - '8428:8428'
    command:
      - -storageDataPath=/vmsingle
      - -promscrape.config=/vmsingle.yml
      - -promscrape.maxScrapeSize=1Gb
    volumes:
      - vmsingle:/vmsingle
      - ./configs/vmsingle/vmsingle.yml:/vmsingle.yml

  grafana:
    image: grafana/grafana:11.6.0
    depends_on:
      - vmsingle
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: true
    ports:
      - '3000:3000'
    volumes:
      - grafanadata:/var/lib/grafana
      - ./configs/grafana/provisioning/:/etc/grafana/provisioning/
      - ./configs/grafana/dashboards:/var/lib/grafana/dashboards/
    restart: always

volumes:
  vmsingle:
  grafanadata:
