version: "3"

services:
  elastic-setup:
    image: curlimages/curl:8.13.0
    entrypoint: sh
    command: /usr/share/elasticsearch/setup.sh
    volumes:
      - ./configs/elasticsearch/setup.sh:/usr/share/elasticsearch/setup.sh
    depends_on:
      elastic:
        condition: service_healthy

  elastic:
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: "8GB"
    image: elasticsearch:8.17.4
    ports:
      - '9200:9200'
    volumes:
      - ./configs/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - elastic-data:/usr/share/elasticsearch/data
    healthcheck:
      test: [ "CMD-SHELL", "curl -f -s http://localhost:9200/_cluster/health | grep 'green'" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      ES_JAVA_OPTS: "-Xmx8192m -XX:+UnlockExperimentalVMOptions -XX:NewRatio=1 -XX:MaxMetaspaceSize=256m -server -XX:+ResizeTLAB -XX:+UseG1GC -XX:+UseStringDeduplication"

  logs-sender:
    image: golang:1.25-alpine
    deploy:
      resources:
        limits:
          memory: "2GB"
    working_dir: /workspace
    volumes:
      - ../:/workspace
      - ./dataset/:/dataset:ro
    command: go run ./benchmarks/cmd/logs-sender
    environment:
      BULK_URL: http://elastic:9200/_bulk
      FILE_PATTERN: "*.log"
      BULK_SIZE: 4096
      INDEX_NAME: logs-index
    depends_on:
      - elastic-setup

volumes:
  elastic-data:
