# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Benchmarks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  issues: write
  contents: write
  pull-requests: write

jobs:
  ci-continuous-benchmarks:
    if: ${{ github.ref_name == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy latest (unstable) version of seq-db
        run: |
          curl --insecure -X POST "https://${{ secrets.CONTINUOUS_BENCHMARKS_ENDPOINT }}/seqagent/v1/b/up" \
            -H "Content-Type: application/json" \
            -H "X-Seqbench-Secret: ${{ secrets.SEQBENCH_SECRET }}" \
            -d @- <<EOF
          {
            "reference": "${{ github.sha }}",
            "scenario": "mixed"
          }
          EOF

  ci-micro-benchmarks:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true

      - name: Run Golang benchmarks
        shell: bash
        run: |
          COUNT=$([[ "${{ github.event_name }}" == "pull_request" ]] && echo 1 || echo 5)
          LOG_LEVEL=FATAL GOMAXPROCS=4 go test -run='$^' -count=$COUNT -bench=. -benchmem ./... | tee ${{ runner.temp }}/gotool.txt

      # Add GitHub job summary for pull requests.
      - name: Summarize benchmarks results
        if: ${{ success() && github.event_name == 'pull_request' }}
        uses: dkharms/chronos@v0.0.10
        with:
          language-tool: gotool
          github-token: ${{ github.token }}
          benchmarks-file-path: ${{ runner.temp }}/gotool.txt
          action-to-perform: summarize

      # Save benchmarks results only when branch
      # was merged to main and previous job was successful.
      - name: Save benchmarks results
        if: ${{ success() && github.ref_name == 'main' }}
        uses: dkharms/chronos@v0.0.10
        with:
          language-tool: gotool
          github-token: ${{ github.token }}
          benchmarks-file-path: ${{ runner.temp }}/gotool.txt
          action-to-perform: save

      # Publish benchmarks results to GitHub pages only when branch
      # was merged to main and previous job was successful.
      - name: Publish benchmarks results
        if: ${{ success() && github.ref_name == 'main' }}
        uses: dkharms/chronos@v0.0.10
        with:
          language-tool: gotool
          github-token: ${{ github.token }}
          action-to-perform: publish
